---
title: "Workspace Rsync Auto Sync Up Your Local With Remote"
dte: 2020-04-18T04:39:36Z
draft: true
---

:projectdir: ../../
:imagesdir: ${projectdir}/assets/
:toclevels: 4
:toc:
:sectnums:
:source-highlighter: coderay
:sectnumlevels: 5

== Workspace Rsync Auto Sync Up Your Local With Remote

=== What is Workspace Rsync ?
Features:

* Automatically sync up my local working space (directories) to remote working space
** Configure your local working directories
** Configure your remote working directories
** configure ssh account with private key to use rsync/scp for download/update files
** Inotify/monitoring changing happend in your local working dir and update to remote working dir
* Support to sync up the whole working dir from remote to local and otherwise
* Support configure file for auto-reload the previous configure
* Saving the configure file to $HOME/.ws-rsync/.config_<name_of_monitoring_workspace>, Auto apply the configuration from
there when user run the utility on configured workspace
* If the local has not the workspace matching with remote side, then ask user to allow for downloading the remote side. And otherwise.
if remote has not the Workspace which existed on local, the ask user to allow for uploading the local version to remote. But I
will follow the simple methology here that Remote Side always have the latest version, The local will always clone workspace from remote side.

=== Getting start

==== Install


[source,shell]
----
#dependency to run ssh with password authentication
sudo apt install sshpass

sudo cp ws-rsync /usr/local/bin
export PATH=$PATH:/usr/local/bin
----

==== Configure and run the utility

[source,shell]
----
# for use ssh key to authentication
ws-rsync config \
    --ssh-acc vu.truong@kencancode.xyz \
    --ssh-port 16022 \
    --ssh-key $HOME/.ssh/id_rsa \
    --local $(pwd) \
    --remote /tmp/ \
    --diff_time 3

# for use ssh password to authentication
//ws-rsync config \
//    --ssh-acc vu.truong@kencancode.xyz \
//    --ssh-port 16022 \
//    --ssh-pass kencancode \
//    --local $(pwd) \
//    --remote /tmp/ \
//    --diff_time 3

ws-rsync start
----

==== Sub-Commands

* `ws-rsync run force_download <workspace_file_path>`
Download file from remote workspace, support relative/absolute path
Examples:
[source,shell]
----
ws-rsync run force_download /home/kevin/Project/KEVIN/Workspace/KenCanCode/version.h
ws-rsync run force_download ./version.h
----

* `ws-rsync run force_upload <workspace_file_path>`
Upload `workspace_file_path` to remote, support relative/absolute path
[source,shell]
----
ws-rsync run force_upload /home/kevin/Project/KEVIN/Workspace/KenCanCode/version.h
ws-rsync run force_upload ./version.h
----

* `ws-rsync run remote_local_sync`
Discard every changes on local and apply remote version for local workspace

* `ws-rsync run local_remote_sync`
Discard every changes on remote and apply local version for remote workspace
